project:
    type: book

book:
    title: "statslab"

    chapters:
    - index.qmd

    - part: "Beginnings"
      chapters:
        - begin/rlang.qmd
        - begin/programming.qmd
        - begin/data.qmd
    - part: "Exploring"
      chapters:
        - explore/dplyr.qmd
    - explore/ggplot2.qmd
    - part: "Regressing"
      chapters:
        - regression/single.qmd
        - regression/multiple.qmd
        - regression/anova.qmd
    - part: "Odds & Ends"
      chapters:
        - other/simulation.qmd
        - other/missingness.qmd

format:
    html:
        theme: cosmo
        css: styles.css
        toc: true