project:
    type: book

book:
    title: "statslab"

    chapters:
    - index.qmd

    - part: beginnings.qmd
      chapters:
        - begin/rlang.qmd
        - begin/data.qmd
        - begin/programming.qmd
        - begin/dplyr.qmd
        - begin/ggplot2.qmd
    - part: regression.qmd
      chapters:
        - regression/single.qmd
        - regression/multiple.qmd
        - regression/anova.qmd
    - part: oddsandends.qmd
      chapters:
        - other/simulation.qmd
        - other/missingness.qmd

format:
    html:
        theme: cosmo
        css: styles.css
        toc: true