project:
    type: book
execute-dir: project

book:
    title: "statslab"

    chapters:
    - index.qmd

    - part: "Beginnings"
      chapters:
        - rlang.qmd
        - programming.qmd
        - data.qmd
    - part: "Exploring"
      chapters:
        - dplyr.qmd
        - ggplot2.qmd
    - part: "Regressing"
      chapters:
        - single.qmd
        - multiple.qmd
        - anova.qmd
    - part: "Odds & Ends"
      chapters:
        - simulation.qmd
        - missingness.qmd

format:
    html:
        theme: cosmo
        css: styles.css
        toc: true