project:
    type: book
    execute-dir: project

book:
    title: "statslab"
    subtitle: "The \"How\" of Statistics"
    author: Christian C. Luhmann
    repo-url: https://github.com/cluhmann/statslab
    reader-mode: true

    navbar:
        logo: images/logos/beta.png
        logo-alt: "Several beta distributions"
        search: false
    search:
        location: sidebar
        type: overlay
    sidebar:
        search: true

    chapters:
    - index.qmd

    - part: "Beginnings"
      chapters:
        - rlang.qmd
        - programming.qmd
        - scripts.qmd
        - data.qmd
    - part: "Exploring"
      chapters:
        - tidyverse.qmd
        - tibbles.qmd
        - dplyr.qmd
        - ggplot2.qmd
    - part: "Statistics"
      chapters:
        - descriptives.qmd
        - hypothesis.qmd
#        - correlation.qmd
#        - single.qmd
#        - multiple.qmd
#        - anova.qmd
#        - interactions.qmd
#        - polynomial.qmd
#        - glm.qmd
    - part: "Odds & Ends"
      chapters:
        - sampling.qmd
        - missingness.qmd
    appendices:
        - references.qmd
        - rannoyances.qmd

bibliography: references.bib

format:
    html:
        theme: sandstone
# theme: sandstone, litera, spacelab, zephyr
        css: styles.css
        toc: true