<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>statslab - 14&nbsp; Basic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./sampling.html" rel="next">
<link href="./distributions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/logos/beta.png" alt="Several beta distributions" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">statslab</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
    <a href="https://github.com/cluhmann/statslab" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./descriptives.html">Statistics</a></li><li class="breadcrumb-item"><a href="./basicregression.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Basic Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Beginnings</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rlang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R &amp; RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R as a Calculator</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scripts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic Programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Working with Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Exploring</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Tidyverse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tibbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dataframes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Manipulating Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualizing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Working with Categorical Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Statistical Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicregression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Basic Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Activities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulatingpre.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distribution of PRE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./samplepvalues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Using <em>p</em>-values to test a hypothesis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Data Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Bibliography</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rannoyances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Running List of Annoying R Things</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-model1" id="toc-sec-model1" class="nav-link active" data-scroll-target="#sec-model1"><span class="header-section-number">14.1</span> Metric-Predicted Variable with One Metric Predictor</a>
  <ul class="collapse">
  <li><a href="#sec-model1table" id="toc-sec-model1table" class="nav-link" data-scroll-target="#sec-model1table"><span class="header-section-number">14.1.1</span> Simple linear regression</a></li>
  <li><a href="#sec-model1points" id="toc-sec-model1points" class="nav-link" data-scroll-target="#sec-model1points"><span class="header-section-number">14.1.2</span> Observed values, fitted values, and residuals</a></li>
  </ul></li>
  <li><a href="#sec-model2" id="toc-sec-model2" class="nav-link" data-scroll-target="#sec-model2"><span class="header-section-number">14.2</span> Metric-Predicted Variable with One Dichotomous Predictor</a>
  <ul class="collapse">
  <li><a href="#model2EDA" id="toc-model2EDA" class="nav-link" data-scroll-target="#model2EDA"><span class="header-section-number">14.2.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model2table" id="toc-sec-model2table" class="nav-link" data-scroll-target="#sec-model2table"><span class="header-section-number">14.2.2</span> Linear regression</a></li>
  <li><a href="#brief-detour-about-factors" id="toc-brief-detour-about-factors" class="nav-link" data-scroll-target="#brief-detour-about-factors"><span class="header-section-number">14.2.3</span> Brief detour about factors</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-basicregression" class="quarto-section-identifier"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Basic Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter makes use of the <code>broom</code> package, part of the tidyverse-adjacent family of packages, <code>tidymodels</code>. It can be installed and loaded in the same way that we have installed/loaded other packages (see <a href="rlang.html#sec-packages"><span>Section&nbsp;1.5</span></a> for a refresher).</p>
</div>
</div>
<section id="sec-model1" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="sec-model1"><span class="header-section-number">14.1</span> Metric-Predicted Variable with One Metric Predictor</h2>
<p>Imagine we are interested in the following research question: what factors explain the average number of points scored by a player per game (i.e., the values in the <code>pts</code> column of our <code>nba</code> data set)? In this section, we’ll keep things simple for now and try to explain <code>pts</code> as a function of one other variable: the average number of assists by a player per game (i.e., the values in the <code>ast</code> column of our <code>nba</code> data set). Could it be that players making more assists will also score more points? We’ll answer this question by modeling the relationship between points and assists using <em>simple linear regression</em> where we have:</p>
<ol type="1">
<li>A numerical outcome variable <span class="math inline">\(y\)</span> (<code>pts</code>) and</li>
<li>A single numerical explanatory variable <span class="math inline">\(x\)</span> (<code>ast</code>).</li>
</ol>
<p>To simplify further, let’s confine our investigation to a small number of teams.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>nba_subset <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">season_int =</span> <span class="fu">substr</span>(nba<span class="sc">$</span>season, <span class="at">start =</span> <span class="dv">1</span>, <span class="at">stop =</span> <span class="dv">4</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(team_abbreviation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"LAL"</span>, <span class="st">"NYK"</span>, <span class="st">"GSW"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It is important to note that the <em>observational unit</em> is an individual player in a given season. Because many players play in more than one season, the same player will appear more than once in the data. Hence there are fewer than 1230 unique players represented in <code>nba_subset</code>. We’ll revisit this idea later, when we talk about the “independence assumption” for inference for regression.</p>
<p>As we saw in <a href="eda.html"><span>Chapter&nbsp;9</span></a>, we can visualize how these two variables are related by generating a scatterplot and a best-fitting trend line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ast, <span class="at">y =</span> pts)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Avg. Assists per Game"</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Avg. Points per Game"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-scatter-line" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="basicregression_files/figure-html/fig-scatter-line-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;14.1: Scatterplot of relationship of assists and points</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="eda.html"><span>Chapter&nbsp;9</span></a>, we did not discuss how this best-fitting trend line was generated. That is the topic of this chapter.</p>
<section id="sec-model1table" class="level3" data-number="14.1.1">
<h3 data-number="14.1.1" class="anchored" data-anchor-id="sec-model1table"><span class="header-section-number">14.1.1</span> Simple linear regression</h3>
<p>You may recall that the equation of a line is <span class="math inline">\(y = a + bx\)</span>. It is defined by two parameters <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The intercept, <span class="math inline">\(a\)</span>, is the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>. The slope, <span class="math inline">\(b\)</span>, is the increase in <span class="math inline">\(y\)</span> for every increase of one in units of <span class="math inline">\(x\)</span>.</p>
<p>When discussing regression, we will often use different notation in which a line is described as <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span>. The intercept is <span class="math inline">\(b_0\)</span>, so <span class="math inline">\(b_0\)</span> is the value of <span class="math inline">\(\widehat{y}\)</span> when <span class="math inline">\(x = 0\)</span>. The slope is <span class="math inline">\(b_1\)</span>, i.e., the increase in <span class="math inline">\(\widehat{y}\)</span> for every increase in one one in <span class="math inline">\(x\)</span>. Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in statistics to indicate that we have an estimate of <span class="math inline">\(y\)</span> rather than <span class="math inline">\(y\)</span> itself.</p>
<p>From inspecting the regression line in <a href="#fig-scatter-line">Figure&nbsp;<span>14.1</span></a>, we know that <span class="math inline">\(b_1\)</span> is positive. Why? Because players who have higher <code>ast</code> values also tend to have higher <code>pts</code> values. However, what is the numerical value of the slope <span class="math inline">\(b_1\)</span>? What about the intercept <span class="math inline">\(b_0\)</span>?</p>
<p>We can obtain values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> by using <em>linear regression</em>. This is done in two steps:</p>
<ol type="1">
<li>We first fit the linear regression model using the <code>lm()</code> function and save it in <code>result</code>.</li>
<li>We get the regression table by applying the <code>get_regression_table()</code> function from the <code>moderndive</code> package to <code>score_model</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the model</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pts <span class="sc">~</span> ast, <span class="at">data =</span> nba)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># get regression table</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pts ~ ast, data = nba)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.3727  -2.9604  -0.8805   2.3586  21.3150 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.17998    0.05748   72.72   &lt;2e-16 ***
ast          2.20111    0.02253   97.69   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.484 on 12303 degrees of freedom
Multiple R-squared:  0.4369,    Adjusted R-squared:  0.4368 
F-statistic:  9544 on 1 and 12303 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s first focus on interpreting the output, and then we’ll later revisit the code that produced it. In the <code>Estimate</code> column are the estimated values of both the intercept, <span class="math inline">\(b_0\)</span>, and slope, <span class="math inline">\(b_1\)</span>. Thus, the equation of the regression line in Figure <a href="#fig-scatter-line">Figure&nbsp;<span>14.1</span></a> is:</p>
<p><span class="math display">\[
\begin{aligned}
    \widehat{y} &amp;= b_0 + b_1 \cdot x\\
    \widehat{pts} &amp;= b_0 + b_{ast} \cdot ast\\
&amp;= 4.17998 + 2.20111 \cdot ast
    \end{aligned}
\]</span></p>
<p>The estiamted value of the intercept, <span class="math inline">\(b_0 = 4.17998\)</span>, is the value of <code>pts</code> expected when <span class="math inline">\(ast=0\)</span>. Or in graphical terms, <span class="math inline">\(b_0 = 4.17998\)</span> indicates where the regression line intersects the <span class="math inline">\(y\)</span> axis when <span class="math inline">\(x=0\)</span>. Note, that the intercept always has a natural a mathematical interpretation, it may well not have a <em>practical</em> interpretation. For example, if <code>x</code> were ratings from a scale that ran 1-7, observing <span class="math inline">\(x=0\)</span> would be impossible.</p>
<p>Typically, the slope <span class="math inline">\(b_1 = b_{ast} = 2.20111\)</span>, is of primary interested, as it summarizes the relationship between <code>ast</code> and <code>pts</code>, the two variables we are investigating. Note that the estimate of <span class="math inline">\(b_1 = b_{ast}\)</span> is positive, suggesting a positive relationship between these two variables, higher <code>ast</code> values seem to imply <code>pts</code>. The other way we might evaluate this relationship would be to calculate a correlation coefficient:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(nba<span class="sc">$</span>pts, nba<span class="sc">$</span>ast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6609489</code></pre>
</div>
</div>
<p>The correlation coefficient and <span class="math inline">\(b_1 = b_{ast}\)</span> are both positive, but are different values. The correlation coefficient’s interpretation is often the “strength of linear association”. The interpretation of <span class="math inline">\(b_1 = b_{ast}\)</span> is a little different:</p>
<blockquote class="blockquote">
<p>For every increase of 1 unit in <code>ast</code>, there is an <em>systematic and corresponding</em> increase of 2.20111 units of <code>pts</code>.</p>
</blockquote>
<p>Note that this statement holds <em>on average</em>. But if you take any two players whose <code>ast</code> values differ by exactly 1 assist, we should not expect their <code>pts</code> values to differ by exactly 2.20111. What <span class="math inline">\(b_1 = b_{ast} = 2.20111\)</span> means is that across all possible players, the <em>average</em> difference in <code>pts</code> between two instructors whose <code>ast</code> values differ by exactly one is 2.20111.</p>
<p>Now that we’ve learned how to compute the equation for the regression line using the estimated values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> and how to interpret the resulting estimates, let’s revisit the code that generated these estimates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pts <span class="sc">~</span> ast, <span class="at">data =</span> nba)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># get regression table</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First, we fit the linear regression model to <code>data</code> (our <code>nba</code> data in this case) using the <code>lm()</code> function and save this as <code>model</code>. When we say “fit”, we mean that we estimate the parameters of our model (<span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> using our data). The function <code>lm()</code> constructs our model for us (<code>lm</code> stands for linear model) and is used as follows: <code>lm(y ~ x, data = data_frame_name)</code> where:</p>
<ul>
<li><code>y</code> is the target variable, followed by a tilde <code>~</code>. In our case, <code>y</code> is set to <code>pts</code>.</li>
<li><code>x</code> is the explanatory variable. In our case, <code>x</code> is set to <code>ast</code>.</li>
<li>The combination of <code>y ~ x</code> is called a <em>model formula</em>. In our case, the model formula is <code>pts ~ ast</code>. Target variables appear on the left hand side of the formula and explanatory variables appear on the right.</li>
<li><code>data_frame_name</code> is the name of the data frame that contains the variables <code>y</code> and <code>x</code>. In our case, <code>data_frame_name</code> is the <code>nba</code> data frame.</li>
</ul>
<p>Second, we take the saved model in <code>model</code> and apply the <code>summary()</code> function to obtain a regression table. The <code>summary()</code> function produces four columns: <code>Estimate</code>, <code>Std. Error</code>, <code>t value</code>, and <code>Pr(&gt;|t|)</code>. These are the estimated value of each model parameter, the standard error of these estimates, the corresponding <span class="math inline">\(t\)</span> values, and associated <span class="math inline">\(p\)</span> values.</p>
</section>
<section id="sec-model1points" class="level3" data-number="14.1.2">
<h3 data-number="14.1.2" class="anchored" data-anchor-id="sec-model1points"><span class="header-section-number">14.1.2</span> Observed values, fitted values, and residuals</h3>
<p>We just saw how to get the value of the intercept and the slope of a regression line from the <code>Estimate</code> column of the regression table generated by the <code>summary()</code> function. Let’s say we instead want information on individual observations. For example, let’s focus on a single player. Specifically, let’s pull out the row of <code>nba</code> that is associated with the Chris Clemons, who appears exactly once in our data set. The corresponding row is illustrated in <a href="#tbl-chrisclemons">Table&nbsp;<span>14.1</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-chrisclemons" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;14.1: Row of Data for Chris Clemons</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">player_name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">pts</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ast</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">season</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chris Clemons</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: left;">2019-20</td>
<td style="text-align: right;">33</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>What is the value <span class="math inline">\(\widehat{y}\)</span> on the regression line corresponding to this player’s <code>ast</code> value of 0.8? In <a href="#fig-numxplot4">Figure&nbsp;<span>14.2</span></a>, we mark three values corresponding to the player and the associated statistical terms:</p>
<ul>
<li>Circle: The <em>observed value</em>, <span class="math inline">\(y\)</span> = 4.9, is this course’s instructor’s actual teaching score.</li>
<li>Square: The <em>fitted value</em>, <span class="math inline">\(\widehat{y}\)</span>, is the value on the regression line that corresponds to <span class="math inline">\(x\)</span> = <code>ast</code> = 0.8. This value is computed using the intercept and slope in the previous regression table:</li>
</ul>
<p><span class="math display">\[\widehat{y} = b_0 + b_1 x =  4.180 + 2.201 \cdot 0.8 = 5.9408753\]</span></p>
<ul>
<li>Arrow: The length of this arrow is the <em>residual</em> and is computed by subtracting the fitted value <span class="math inline">\(\widehat{y}\)</span> from the observed value <span class="math inline">\(y\)</span>. The residual can be thought of as the error the model generates for a particular observation. In the case of this course’s player, the residual is <span class="math inline">\(y - \widehat{y}\)</span> = 4.9 - 5.9408753 = -1.0408753.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-numxplot4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="basicregression_files/figure-html/fig-numxplot4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;14.2: Example of observed value, fitted value, and residual.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now say we want to compute both the fitted value, <span class="math inline">\(\widehat{y} = b_0 + b_1 x\)</span>, and the residual, <span class="math inline">\(y - \widehat{y}\)</span>, for <em>all</em> 12305 rows in our <code>nba</code> data set. We could repeat the previous calculations we performed by hand 12305 times, but that would be somewhat time-consuming. Instead, let’s do this using a computer with the <code>get_regression_points()</code> function. Just like the <code>get_regression_table()</code> function, the <code>get_regression_points()</code> function is a “wrapper” function. However, this function returns a different output. Let’s apply the <code>get_regression_points()</code> function to <code>score_model</code>, which is where we saved our <code>lm()</code> model in the previous section. In Table @ref(tab:regression-points-1) we present the results of only the 21st through 24th courses for brevity’s sake.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># expand model result</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># select relevant columns</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"pts"</span>, <span class="st">"ast"</span>, <span class="st">".fitted"</span>, <span class="st">".resid"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># rename columns</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename_at</span>(<span class="fu">vars</span>(<span class="fu">c</span>(<span class="st">".fitted"</span>, <span class="st">".resid"</span>)), <span class="sc">~</span><span class="fu">c</span>(<span class="st">"pts_hat"</span>, <span class="st">"residual"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,305 × 4
     pts   ast pts_hat residual
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1   5.7   3.1   11.0     -5.30
 2   2.3   0.3    4.84    -2.54
 3   0.8   0.4    5.06    -4.26
 4   3.7   0.6    5.50    -1.80
 5   2.4   0.2    4.62    -2.22
 6   8.2   1      6.38     1.82
 7  17.2   3.4   11.7      5.54
 8  14.9   1.6    7.70     7.20
 9   5.7   1.3    7.04    -1.34
10   6.9   3     10.8     -3.88
# ℹ 12,295 more rows</code></pre>
</div>
</div>
<p>Let’s inspect the individual columns and match them with the elements of <a href="#fig-numxplot4">Figure&nbsp;<span>14.2</span></a>:</p>
<ul>
<li>The <code>pts</code> column represents the observed outcome variable, <span class="math inline">\(y\)</span>. This column contains the y-position of the 12305 gray data points.</li>
<li>The <code>ast</code> column represents the values of the explanatory variable, <span class="math inline">\(x\)</span>. This is the x-position of the 12305 gray data points.</li>
<li>The <code>pts_hat</code> column represents the fitted values <span class="math inline">\(\widehat{y}\)</span>. This is the corresponding value on the regression line for the 12305 <span class="math inline">\(x\)</span> values.</li>
<li>The <code>residual</code> column represents the residuals <span class="math inline">\(y - \widehat{y}\)</span>. This is the 12305 vertical distances between the 12305 black points and the regression line.</li>
</ul>
<p>Just as we did for Chris Clemons’ single row from <code>nba</code>, one can now repeat the calculations for any particular data point (row) in the <code>nba</code> data set or, if you so wish, do so for <em>all</em> rows.</p>
<p>In a bit, we’ll talk about how conventional (“ordinary least squares”) regression takes each of these residuals, squares them (so they are all positive), and finds the model parameters (e.g., <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>) that minimize their sum.</p>
</section>
</section>
<section id="sec-model2" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="sec-model2"><span class="header-section-number">14.2</span> Metric-Predicted Variable with One Dichotomous Predictor</h2>
<p>Let’s take a step back now and consider a somewhat simpler scenario. Imagine two basketball fans are arguing over who is the better player, Stephen Curry or LeBron James. Curry is a fantastic shooter, but James has more offensive tools at his disposal (e.g., he is much larger and physically stronger). How can we use data to help provide some evidence for this debate? One way we can do so is to compare the average points per game scored by each player (i.e., the data in the <code>pts</code> column of our <code>nba</code> data set). Let’s do that.</p>
<section id="model2EDA" class="level3" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="model2EDA"><span class="header-section-number">14.2.1</span> Exploratory data analysis</h3>
<p>Let’s begin with an exploration of the relevant data. We can do this is a couple of different ways (see <a href="eda.html"><span>Chapter&nbsp;9</span></a> for options). For example, we can begin by looking at the data itself.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(player_name, pts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 2
   player_name     pts
   &lt;chr&gt;         &lt;dbl&gt;
 1 LeBron James   20.9
 2 LeBron James   27.2
 3 LeBron James   31.4
 4 LeBron James   27.3
 5 LeBron James   30  
 6 LeBron James   28.4
 7 Stephen Curry  17.5
 8 LeBron James   29.7
 9 Stephen Curry  18.6
10 LeBron James   26.7
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>Here, we see the <code>pts</code> column that we are focusing on and the players’ names. There are only a few rows of data here, so viewing the first few rows gives us a decent sense of what the relevant data looks like. If we had a large number of rows or if the rows were ordered in a particular way (e.g., all of Stephen Curry’s rows were grouped before all of LeBron James’ rows), then we might instead wish to view a random sample of rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(player_name, pts) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sample_n</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   player_name     pts
   &lt;chr&gt;         &lt;dbl&gt;
 1 LeBron James   25.3
 2 LeBron James   26.8
 3 LeBron James   27.3
 4 LeBron James   26.4
 5 LeBron James   25.3
 6 LeBron James   26.7
 7 LeBron James   27.4
 8 Stephen Curry  18.6
 9 LeBron James   30.3
10 Stephen Curry  24  </code></pre>
</div>
</div>
<p>Another way to get a sense of this data is by generating a variety of descriptive statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(player_name, pts) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(player_name) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">m =</span> <span class="fu">mean</span>(pts),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">sd =</span> <span class="fu">sd</span>(pts),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">min =</span> <span class="fu">min</span>(pts),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"%25 Q"</span> <span class="ot">=</span> <span class="fu">quantile</span>(pts, .<span class="dv">25</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"%50 Q"</span> <span class="ot">=</span> <span class="fu">quantile</span>(pts, .<span class="dv">5</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"%75 Q"</span> <span class="ot">=</span> <span class="fu">quantile</span>(pts, .<span class="dv">75</span>),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">max =</span> <span class="fu">max</span>(pts)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  player_name       m    sd   min `%25 Q` `%50 Q` `%75 Q`   max
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 LeBron James   27.1  2.35  20.9    25.8    27.1    28.0  31.4
2 Stephen Curry  23.8  4.92  14.7    20.8    24      26.4  32  </code></pre>
</div>
</div>
<p>Here, we observe that the LeBron James’ average across seasons is 27.1 whereas Stephen Curry’s average is 23.8. Indeed, James has higher values than Curry at each quantile as well. Let’s visualize the actual distribution that these summary statistics describe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> pts, <span class="at">fill =</span> player_name)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">position =</span> <span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="basicregression_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Some people prefer comparing the distributions of a numerical variable between different levels of a categorical variable using a boxplot instead of a faceted histogram. This is because we can make quick comparisons between the categorical variable’s levels with imaginary horizontal lines. This is particularly true when the categorical variable of interest takes on many levels. Let’s take a quick look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> player_name, <span class="at">y =</span> pts)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Player"</span>, <span class="at">y =</span> <span class="st">"Avg. Points per Game"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="basicregression_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This visualization reiterates that LeBron James’ median (the solid line in the middle of the left box) are greater than Stephen Curry’s, but we can also more easily see that Stephen Curry’s values are more spread out; there is greater variability in Curry’s <code>pts</code> values across seasons.</p>
<p>All of these explorations seem to suggest that LeBron James is a better scorer than Stephen Curry. But we really need some inferential statistics to determine whether the difference between the two players’ means is large enough to convince us to reject the null hypothesis that the two players’ means are equal (and treat LeBron James’ mean as larger than Stephen Curry’s mean).</p>
</section>
<section id="sec-model2table" class="level3" data-number="14.2.2">
<h3 data-number="14.2.2" class="anchored" data-anchor-id="sec-model2table"><span class="header-section-number">14.2.2</span> Linear regression</h3>
<p>In <a href="#sec-model1table"><span>Section&nbsp;14.1.1</span></a>, we introduced simple linear regression, which involves modeling the relationship between a numerical outcome variable <span class="math inline">\(y\)</span> and a numerical explanatory variable <span class="math inline">\(x\)</span>. In the current situation, we instead have a categorical explanatory variable <code>player_name</code>. Furthermore, this categorical variable takes on exactly two values (i.e., “LeBron James” and “Stephen Curry”), which means that our explanatory variable is <em>dichotomous</em>.</p>
<p>Before we begin putting our regression model together, let’s grab the relevant data and save into a variable for less verbose code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>curryjames <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(player_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Stephen Curry"</span>, <span class="st">"LeBron James"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">c</span>(pts, player_name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can construct the model, fit it to the data, and summarize our results as we did before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>curryjames_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pts <span class="sc">~</span> player_name, <span class="at">data =</span> curryjames)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(curryjames_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pts ~ player_name, data = curryjames)

Residuals:
   Min     1Q Median     3Q    Max 
-9.062 -1.810  0.064  1.951  8.239 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               27.1105     0.8268  32.790   &lt;2e-16 ***
player_nameStephen Curry  -3.3490     1.2972  -2.582    0.015 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.604 on 30 degrees of freedom
Multiple R-squared:  0.1818,    Adjusted R-squared:  0.1545 
F-statistic: 6.665 on 1 and 30 DF,  p-value: 0.01496</code></pre>
</div>
</div>
<p>We have two rows in our regression table: <code>(Intercept)</code> and <code>player_nameStephen Curry</code>. We specified our model as <code>pts ~ player_name</code>. But what exactly is happening behind the scenes? One way to investigate is to look at the design matrix that <code>lm()</code> has constructed on our behalf:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(curryjames_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) player_nameStephen Curry
1            1                        0
2            1                        0
3            1                        0
4            1                        0
5            1                        0
6            1                        0
7            1                        1
8            1                        0
9            1                        1
10           1                        0
11           1                        1
12           1                        0
13           1                        1
14           1                        0
15           1                        1
16           1                        0
17           1                        0
18           1                        1
19           1                        0
20           1                        1
21           1                        1
22           1                        0
23           1                        1
24           1                        0
25           1                        1
26           1                        0
27           1                        0
28           1                        1
29           1                        0
30           1                        1
31           1                        1
32           1                        0
attr(,"assign")
[1] 0 1
attr(,"contrasts")
attr(,"contrasts")$player_name
[1] "contr.treatment"</code></pre>
</div>
</div>
<p>To better understand how this design matrix encodes our raw data, we can squash to two together for easy comparison:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_cols</span>(curryjames, <span class="fu">model.matrix</span>(curryjames_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 4
     pts player_name   `(Intercept)` `player_nameStephen Curry`
   &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;                      &lt;dbl&gt;
 1  20.9 LeBron James              1                          0
 2  27.2 LeBron James              1                          0
 3  31.4 LeBron James              1                          0
 4  27.3 LeBron James              1                          0
 5  30   LeBron James              1                          0
 6  28.4 LeBron James              1                          0
 7  17.5 Stephen Curry             1                          1
 8  29.7 LeBron James              1                          0
 9  18.6 Stephen Curry             1                          1
10  26.7 LeBron James              1                          0
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>Now we can see that <code>lm()</code> has constructed a design matrix with two columns (one named <code>(Intercept)</code> and one named <code>player_nameStephen Curry</code>). Every value in the intercept column is 1. The values in the <code>player_nameStephen Curry</code> column are 1 where <code>player_name == Stephen Curry</code> and 0 where <code>player_name == LeBron James</code>.</p>
<p>Let’s now write the equation for our fitted values <span class="math inline">\(\widehat{y} = \widehat{\text{pts}}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{pts} &amp;= b_0 + b_1\cdot\mathbb{1}_{\text{Curry}}(x)
\end{aligned}
\]</span></p>
<p>What is happening here? First, <span class="math inline">\(\mathbb{1}_{A}(x)\)</span> is what’s known in mathematics as an “indicator function”. It returns only one of two possible values, 0 and 1, where</p>
<p><span class="math display">\[
\mathbb{1}_{A}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } x \text{ is in } A \\
0 &amp; \text{if } \text{otherwise} \end{array}
\right.
\]</span></p>
<p>In a statistical modeling context, this is also known as a <em>dummy variable</em>. In our case, the indicator variable <span class="math inline">\(\mathbb{1}_{\text{Curry}}(x)\)</span> returns 1 if a row of data corresponds to an observation associated with Stephan Curry and 0 otherwise (which is exactly what is in the <code>curry</code> column of our design matrix above):</p>
<p><span class="math display">\[
\mathbb{1}_{\text{Curry}}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } \text{player } x \text{ is Stephen Curry} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span></p>
<p>Thus, we can consider two different scenarios. The first, is what the model looks like when we are considering observations from LeBron James. At that point, <span class="math inline">\(\mathbb{1}_{\text{Curry}}(x)=0\)</span>, so the model reduces to:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{pts} &amp;= b_0 + b_1\cdot\mathbb{1}_{\text{Curry}}(x) \\
\widehat{pts} &amp;= b_0 + b_1\cdot 0 \\
\widehat{pts} &amp;= b_0
\end{aligned}
\]</span></p>
<p>This suggests that <span class="math inline">\(b_0\)</span> represents our expectation about the value of <code>pts</code> associated with LeBron James. Now let’s consider what the model looks like when we are considering observations from Stephen Curry. At that point, <span class="math inline">\(\mathbb{1}_{\text{Curry}}(x)=1\)</span>, so the model is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{pts} &amp;= b_0 + b_1\cdot\mathbb{1}_{\text{Curry}}(x) \\
\widehat{pts} &amp;= b_0 + b_1\cdot 1 \\
\widehat{pts} &amp;= b_0 + b_1
\end{aligned}
\]</span></p>
<p>So what does this suggest about the interpretation of <span class="math inline">\(b_1\)</span>? Well we already said that <span class="math inline">\(b_0\)</span> is our expectation about LeBron James’ value of <code>pts</code>. And our expectation about Stephen Curry’s value of <code>pts</code> is <span class="math inline">\(b+0 + b_1\)</span>. This implies that <span class="math inline">\(b_1\)</span> represents the <strong>difference</strong> between those two expectations: we expect Stephen Curry’s <code>pts</code> to be <span class="math inline">\(b_1\)</span> points greater than LeBron James’ <code>pts</code>. You may also think of <span class="math inline">\(b_1\)</span> as an <strong>offset</strong>.</p>
<p>So returning to our regression table, we can see that the table indicates that <span class="math inline">\(b_0=27.1105\)</span> and <span class="math inline">\(b_1=-3.3490\)</span>. So we should expect that LeBron James’ <code>pts</code> values are 27.11 on average. Furthermore, we should expect that Stephen Curry’ <code>pts</code> values should be 3.35 points <strong>less</strong> than LeBron James’ (less because the coefficient is negative). Let’s compare that to the means of the actual data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>curryjames <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(player_name) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(pts))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  player_name    mean
  &lt;chr&gt;         &lt;dbl&gt;
1 LeBron James   27.1
2 Stephen Curry  23.8</code></pre>
</div>
</div>
<p>So our coefficient values and the interpretation we described above seem to match.</p>
<p>You might be asking at this point why was LeBron James chosen as the “baseline” and Stephen Curry appears in the model as an offset. This is the case for no other reason than LeBron James appears first in our <code>curryjames</code> data frame. Good question.</p>
<p>It turns out that we have allows the <code>lm()</code> function to do some “bookkeeping” work on our behalf. When we look at our data, we see that the <code>player_name</code> column is <code>&lt;chr&gt;</code>, or a character vector (aka, a string). But we can’t really do math on strings. So what we really need to do is convert these strings into a <strong>categorical variable</strong>. To do this, we can use R’s <strong>factors</strong>.</p>
</section>
<section id="brief-detour-about-factors" class="level3" data-number="14.2.3">
<h3 data-number="14.2.3" class="anchored" data-anchor-id="brief-detour-about-factors"><span class="header-section-number">14.2.3</span> Brief detour about factors</h3>
<p>When you have a column that is a character vector (or other data type) and you wish to treat it as a categorical variable, you can use the tidyverse package <code>forcats</code>. One of the core functions in the <code>forcats</code> package is <code>fct()</code>. This function does exactly what we need: converts a vector as a factor or categorical variable. Let’s see what <code>fct()</code> does for our <code>player_name</code> column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fct</span>(curryjames<span class="sc">$</span>player_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] LeBron James  LeBron James  LeBron James  LeBron James  LeBron James 
 [6] LeBron James  Stephen Curry LeBron James  Stephen Curry LeBron James 
[11] Stephen Curry LeBron James  Stephen Curry LeBron James  Stephen Curry
[16] LeBron James  LeBron James  Stephen Curry LeBron James  Stephen Curry
[21] Stephen Curry LeBron James  Stephen Curry LeBron James  Stephen Curry
[26] LeBron James  LeBron James  Stephen Curry LeBron James  Stephen Curry
[31] Stephen Curry LeBron James 
Levels: LeBron James Stephen Curry</code></pre>
</div>
</div>
<p>It doesn’t really look like <code>fct()</code> has done too much to our column. The only real addition is the “Levels: LeBron James Stephen Curry” at the bottom. Note that “LeBron James” comes before “Stephen Curry” here. That’s an indication of the order in which the 2 levels exist in the factor. To gain direct control over how <code>player_name</code> is used as a predictor in our regression model, we can create a new column that is a factor version of the <code>player_name</code> column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>curryjames<span class="sc">$</span>player_name.f <span class="ot">&lt;-</span> <span class="fu">fct</span>(curryjames<span class="sc">$</span>player_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s use this new variable as our predictor and see what happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(pts <span class="sc">~</span> curryjames<span class="sc">$</span>player_name.f, <span class="at">data=</span>curryjames))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pts ~ curryjames$player_name.f, data = curryjames)

Residuals:
   Min     1Q Median     3Q    Max 
-9.062 -1.810  0.064  1.951  8.239 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                            27.1105     0.8268  32.790   &lt;2e-16 ***
curryjames$player_name.fStephen Curry  -3.3490     1.2972  -2.582    0.015 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.604 on 30 degrees of freedom
Multiple R-squared:  0.1818,    Adjusted R-squared:  0.1545 
F-statistic: 6.665 on 1 and 30 DF,  p-value: 0.01496</code></pre>
</div>
</div>
<p>Other than the slightly more verbose name of our predictor (<code>curryjames$player_name.fStephen Curry</code>), the results are the same. Using another <code>forcats</code>, we can instead construct our <code>player_name</code> factor so that Stephen Curry is used as the baseline:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>curryjames<span class="sc">$</span>player_name.f <span class="ot">&lt;-</span> <span class="fu">fct_rev</span>(curryjames<span class="sc">$</span>player_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>fct_rev()</code> function is just like <code>fct()</code>, but it reverses the order of the levels on the factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(pts <span class="sc">~</span> curryjames<span class="sc">$</span>player_name.f, <span class="at">data=</span>curryjames))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pts ~ curryjames$player_name.f, data = curryjames)

Residuals:
   Min     1Q Median     3Q    Max 
-9.062 -1.810  0.064  1.951  8.239 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           23.7615     0.9995  23.772   &lt;2e-16 ***
curryjames$player_name.fLeBron James   3.3490     1.2972   2.582    0.015 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.604 on 30 degrees of freedom
Multiple R-squared:  0.1818,    Adjusted R-squared:  0.1545 
F-statistic: 6.665 on 1 and 30 DF,  p-value: 0.01496</code></pre>
</div>
</div>
<p>Let’s generalize this idea a bit. If we fit a linear regression model using a categorical explanatory variable <span class="math inline">\(x\)</span> that has <span class="math inline">\(k\)</span> possible categories, the regression table will return an intercept and <span class="math inline">\(k - 1\)</span> “offsets”. In our case, since there are <span class="math inline">\(k = 2\)</span> players in our reduced <code>curryjames</code> data set, the regression model returns an intercept corresponding to the baseline for one player and <span class="math inline">\(k - 1 = 1\)</span> offsets corresponding to the other.</p>
<p>Understanding a regression table output when you’re using a categorical explanatory variable is a topic those new to regression often struggle with. The only real remedy for these struggles is practice, practice, practice. However, once you equip yourselves with an understanding of how to create regression models using categorical explanatory variables, you’ll be able to incorporate many new variables into your models, given the large amount of the world’s data that is categorical.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./distributions.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Statistical Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./sampling.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sampling</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>