# Introduction {.unnumbered}

Content covering statistics, data analysis, and computer programming.  Sections are listed on the left.


**Instructor**

Christian Luhmann

**Teaching Assistant**

Tracy Radsvick


## Schedule

_Subject to change_, particularly topics scheduled for later in the semester.

| Week | Date | Lecture | Activity |
|---|---|---|---|
| 1 | 09-01 | R & Rstudio, Basic Programming |  |
| 2 | 09-08 | Adv. Programming and Handling Data in R |  |
| 3 | 09-15 | The Tidyverse, Tibbles |  |
| 4 | 09-22 | **Christian Out of Town** | Review of material to date |
| 5 | 09-29 | Data Wrangling with dplyr |  |
| 6 | 10-06 |  | Sampling |
| 7 | 10-13 | Plotting with ggplot2 |  |
| 8 | 10-20 |  | `rep_sample_n()` from scratch |
| 9 | 10-27 |  | Simulating the PRE sampling distribution |
| 10 | 11-03 | Basic Regression 1/2 | |
| 11 | 11-10 | Basic Regression 2/2 | Generate random data & regress!  |
| 12 | 11-17 | Regression Diagnostics | Tests of normality |
| 13 | 11-24 | **No Class – Thanksgiving Break** | |
| 14 | 12-01 | Class aborted |  |
| 15 | 12-08 | Multiple Regression 1/N |  |
|  | | **Winter Break** |  |
| 16 | 1-26 | Refresh | |
| 17 | 2-2 |  | End-to-end Analysis |
| 18 | 2-9 | Sampling: p-values ala Lakens | |
| 19 | 2-16 | Interactions | |
| 20 | 2-23 | Linear Mixed Models  | |
| 21 | 3-1 | Categorical Variables  | |
| 22 | 3-8 | Missingness  | |
| 23 | 3-15 | Model comparison | |
| 24 | 3-22 | GLM  | |
| 25 | 3-29 | Machine Learning | |
| 26 | 4-5 | Machine Learning | |
| 27 | 4-12 | Bayesian Stuff | |
| 28 | 4-19 | Bayesian Stuff | |
| 29 | 4-26 | Python  | |
| 30 | 5-3 | Julia  | |
